# @package _global_

defaults:
  - base_config
  - _self_
  - run: local

common:
  fp16: false

data:
  base_data_dir: ???
  dataset_names: ???
  video_backend: pyav
  num_frames: 128
  sampling_rate: 2
  target_fps: 25
  min_duration: 1.0
  max_duration: 40.0
  rand_aug: true
  repeat_aug: 2

wandb:
  enabled: true
  project: ssvp-pretraining

optim:
  batch_size: 1
  gradient_accumulation_steps: 1
  warmup_epochs: 120
  epochs: 400
  lr: 8e-4
  min_lr: 1e-6