# @package _global_

defaults:
  - base_config
  - _self_
  - run: local

common:
  eval_print_samples: true
  fp16: true
  eval_steps: 500

model:
  name_or_path: facebook/bart-base
  feature_dim: 768
  from_scratch: false
  dropout: 0.3

data:
  train_data_dirs: ???
  val_data_dir: ???
  num_epochs_extracted: 1
  min_source_positions: 5
  max_source_positions: 1024
  max_target_positions: 128

wandb:
  enabled: true
  project: ssvp-bart

optim:
  train_batch_size: 8
  val_batch_size: 32
  gradient_accumulation_steps: 1
  warmup_epochs: 2
  epochs: 100
  lr: 5e-4
  min_lr: 1e-7
  early_stopping: true
  patience: 25

criterion:
  label_smoothing: 0.2
